//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airportmng.Models.DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AirPortDatabaseEntities8 : DbContext
    {
        public AirPortDatabaseEntities8()
            : base("name=AirPortDatabaseEntities8")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Addresstable> Addresstables { get; set; }
        public virtual DbSet<Hanger_table> Hanger_table { get; set; }
        public virtual DbSet<ManagerTable> ManagerTables { get; set; }
        public virtual DbSet<Pilot_table> Pilot_table { get; set; }
        public virtual DbSet<Plane_hanger> Plane_hanger { get; set; }
        public virtual DbSet<Plane_pilot> Plane_pilot { get; set; }
        public virtual DbSet<Plane_table> Plane_table { get; set; }
        public virtual DbSet<Planeowner_table> Planeowner_table { get; set; }
        public virtual DbSet<Admintable> Admintables { get; set; }
    }
}
