//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airportmng.Models.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plane_pilot
    {
        public int ID { get; set; }
        public string Plane_id { get; set; }
        public string Pilot_id { get; set; }
    
        public virtual Pilot_table Pilot_table { get; set; }
        public virtual Plane_table Plane_table { get; set; }
    }
}
