//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Airportmng.Models.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plane_hanger
    {
        public int ID { get; set; }
        public string Hanger_Id { get; set; }
        public string Plane_Id { get; set; }
        public System.DateTime fromdate { get; set; }
        public System.DateTime todate { get; set; }
    
        public virtual Hanger_table Hanger_table { get; set; }
        public virtual Plane_table Plane_table { get; set; }
    }
}
